# Generated by Django 4.1.7 on 2023-03-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='autorUser',
            new_name='authorUser',
        ),
    ]
